name: Github Action with a cronjob trigger
on:
  schedule:
    - cron: '0 0 */10 * *'  # 每隔十天执行一次，精确到 UTC 时间的午夜
  workflow_dispatch:
    inputs:
      mode:
        description: 'Force Mode'
        required: true
        default: Y
        type: choice
        options:
          - Y
          - N
permissions:
  contents: write
jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - step1
      # - step 2
      # - step n, use it as the last step
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
