export default [
  'Vontar X2',
  // 'X98 S500',
  // 'Vontar X4',
  'X96 X4',
  // 'X98 mini',
  // 'Transpeed AV1',
  // 'Tanix W2',
  // 'Tanix X4',
  // 'X96Max Plus Ultra',
  'Kingnovel X10 MAX',
  'A95X F4',
  'TranSpeed X4, X4S',
  'X96Max Plus',
  'Beelink GT King II',
  'X96 mini',
  'Beelink GS-King X',
  'Мегафон M8S Pro+',
  'Mecool M8S Pro',
  'Okko Smart Box',
  'MINIX Neo U9-H',
  'Bqeel Y8 Max',
  'WIFIRE Q5',
  'X98 Pro',
  // 'X88 King',
  // 'Vorke Z1',
  // 'Minix NEO U22-XJ Max',
  // 'Beelink GT-King',
  // 'YokaTV KB2 Pro',
  // 'Tanix TX9S',
  // 'Minix NEO U22-XJ',
  // 'Tronsmart Vega S96',
  // 'X92',
  // 'Beelink GT-King Pro',
  'H96 Pro plus',
  // 'Ugoos AM3', xxxx
  // 'Mecool BB2 and Pro',
  // 'X96 Max',
  // 'MECOOL KIII Pro',
  // 'X96S tv Stick',
  // 'Dealdig BOXD6',
  // 'T95Q',
  // 'Beelink GT1 Mini',
  // 'A95X F2',
  // 'Beelink GT1 Ultimate',
  // 'Magicsee N5 Max X2',
  // 'Amlogic s905x',
  // 'Beeline RASSE-001',
  // 'X96 mini 5G',
  // 'X96 mini Plus',
  // 'Openbox A4Pro',
  'TX3 Mini',
  'X99 Max Plus',
  'Tanix TX3',
  'X96Air',
  'Magicsee N5 Max X3',
  'HK1 Box',
  'Vontar X3',
  'H9 X3',
  'Transpeed X3 Air, Plus, Pro',
  'Tanix TX5 PLUS',
  'H96 Max X3',
  'EACHLINK X3 mini',
  'T96Z',
  'T95Q MAX X3',
  'X88 Pro X3 (не шифрованный)',
  'Beelink GT1 Mini2',
  'A95X MAX II',
  'S9 Max',
  'IE X3 Air', // xxx
  'AX95 DB',
  'A95X F3, Air, Slim',
  'Magicsee N6 Plus',
  'TOX1',
  'A95X W2',
  'Ugoos X4 Pro',
  'Zoomtak King S22',
  'Ugoos AM6, PRO, Plus, ревизия B',
  'Ugoos X3 Cube, Pro',
  'Ugoos X2 Cube, Pro',
  'Mecool KM9',
  'Vosen V1',
  'Smart Box Z1'
]
