name: update data

on: push

jobs:
  build:
    name: update data info files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # - uses: ianwalter/puppeteer-container@v4.0.0
      - run: npm install
      - run: npm run start
 
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main
          folder: output
          clean: false
          force: false
          # clean-exclude: true
          commit-message: update json file by action