name: update data

on: push

jobs:
  build:
    name: update data info files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run update
 
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main
          folder: output
          clean: false
          force: false
          # clean-exclude: true
          commit-message: update json file by action