name: test

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        type: environment
        description: Select the script
        options:
        - dev
        - test
        - prod
      boolean:
        type: boolean
        default: true
        description: True or False
      choice:
        type: choice
        description: Make a choice
        default: 'foo'
        options:
        - foo
        - bar
        - baz

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node test.js --${{github.event.inputs.name}}
      - run: npm run test --${{github.event.inputs.name}}
      - run: echo "hello ${{github.event.inputs.name}}"